<?php

return [
    /*
     * Version of the Highcharts library loaded from code.highcharts.com.
     * Pinned so that a new Highcharts major release cannot silently
     * break existing charts.
     */
    'highcharts_version' => '12.6.0',

    'chart_options' => [
        'Area',
        'Arearange',
        'Areaspline',
        'Areasplinerange',
        'Bar',
        'Bellcurve',
        'Boxplot',
        'Bubble',
        'Bullet',
        'Column',
        'Columnpyramid',
        'Columnrange',
        'Cylinder',
        'Dependencywheel',
        'Dumbbell',
        'Errorbar',
        'Funnel',
        'Funnel3d',
        'Gauge',
        'Heatmap',
        'Histogram',
        'Item',
        'Line',
        'Lollipop',
        'Networkgraph',
        'Organization',
        'Packedbubble',
        'Pareto',
        'Pictorial',
        'Pie',
        'Polygon',
        'Pyramid',
        'Pyramid3d',
        'Sankey',
        'Scatter',
        'Scatter3d',
        'Solidgauge',
        'Spline',
        'Streamgraph',
        'Sunburst',
        'Tilemap',
        'Timeline',
        'Treegraph',
        'Treemap',
        'Variablepie',
        'Variwide',
        'Vector',
        'Venn',
        'Waterfall',
        'Windbarb',
        'Wordcloud',
        'Xrange',
        'Arcdiagram',
    ],
];
